### ISSUE TITLE
Support for Failables?

### ISSUE THREAD

**Issue by umairsuraj** [marksands/BetterCodable#11]
`let json = """
[
    {"name": "Taro", "age": 20},
    {"name": "Hanako"}
]
""".data(using: .utf8)! // Hanako has no "age"`

**Comment by marksands** [comment]
I'm not sure what you're expected behavior is. Would you want to silently fail "Hanako", or would you want the parsing to throw?

There's a `@LossyArray` type that you can use, if your data has a root key. If the array is the root then you can use `LossyArray` as the decodable type.

```
let json = #"[ {"name": "Taro", "age": 20}, {"name": "Hanako"}]"#.data(using: .utf8)! // Hanako has no "age"

struct NameAndAge: Codable {
    let name: String
    let age: Int
}

let results = try JSONDecoder().decode(LossyArray<NameAndAge>.self, from: json)
print(results.wrappedValue) // [{ name: "Taro", age: 20 }]
```
