### ISSUE TITLE
Custom Date Value Wrapper

### ISSUE THREAD

**Issue by umairsuraj** [marksands/BetterCodable#12]
Is there any option for decoding entities that have custom date formats?

**Comment by marksands** [comment]
Yes, definitely possible. Make a type that conforms to `DateValueCodableStrategy` (see https://github.com/marksands/BetterCodable/blob/master/Sources/BetterCodable/DateValue.swift#L6-L11) And use it like so:

```
struct Response: Codable {
    @DateValue<SomeCustomDateFormatterStrategy> var someDate: Date
    @DateValue<OtherCustomDateFormatterStrategy> var otherDate: Date
}
```

For inspiration, take a look at [YearMonthDayStrategy](https://github.com/marksands/BetterCodable/blob/master/Sources/BetterCodable/YearMonthDayStrategy.swift) and [RFC2822Strategy](https://github.com/marksands/BetterCodable/blob/master/Sources/BetterCodable/RFC2822Strategy.swift).

**Comment by alexj70** [comment]
Hi. Is it possible to use optional value for the date property?
