### ISSUE TITLE
@DefaultFalse when key is missing

### ISSUE THREAD

**Issue by herrernst** [marksands/BetterCodable#16]
I have an API which either sends {"bool":true} or no key at all. But I still like to have a non-optional Bool in my Codable class because I have to access it from Objective-C (which can't access optional Bools). Is that possible somehow? Thanks.

**Comment by marksands** [comment]
You can write a custom decoder implementation to accomplish that, but I'm not sure if there's a simple solution via `propertyWrapper`. I'd have to think about what that would look like. 🤔

**Comment by herrernst** [comment]
Thanks for your feedback!

**Comment by marksands** [comment]
Closed with #17

**Comment by herrernst** [comment]
Thank you!
