### ISSUE TITLE
@DefaultCodable<> not working as expected?

### ISSUE THREAD

**Issue by abrownsword** [marksands/BetterCodable#18]
`
struct DefToZero: DefaultCodableStrategy {
	static var defaultValue: Double { 0.0 }
}

struct T : Hashable, Equatable, Codable {
	@DefaultCodable<DefToZero>	var a : Double = 0.0
	@DefaultCodable<DefToZero>	var b : Double = 0.0
}

struct C : Hashable, Equatable, Codable {
	var t : T
}
`

When I run this, however, I get...

`CodingKeys(stringValue: "a", intValue: nil) in Context(codingPath: [CodingKeys(stringValue: "t", intValue: nil), debugDescription: "No value associated with key CodingKeys(stringValue: \"a\", intValue: nil) (\"a\").", underlyingError: nil)`

I've simplified things a bit, but this retains the jist.  Should nested structs like this work?  Am I right in expecting this to decode from a JSON that is missing the a member of the substruct t?

**Comment by marksands** [comment]
Hi @abrownsword. The `DefaultCodableStrategy` is to be used as a generic type for `DefaultCodable`. What you have should be used as `@DefaultCodable<DefToZero>`. 

For completion:

```swift
struct DefToZero: DefaultCodableStrategy {
  static var defaultValue: Double { 0.0 }
}

typealias DefaultToZero = DefaultCodable<DefToZero>

struct T: Hashable, Equatable, Codable {
  @DefaultToZero var a: Double
  @DefaultToZero var b: Double
}

struct C : Hashable, Equatable, Codable {
  var t: T
}

let json = #"{ "t": { "a": null, "b": null } }"#.data(using: .utf8)!
let c = try! JSONDecoder().decode(C.self, from: json)
c.t.a // 0.0
c.t.b // 0.0
```

**Comment by abrownsword** [comment]
Thanks, Mark, but I rearranged the code as you suggested and still get the same problem.

**Comment by marksands** [comment]
It works with the simplified solution, so it's likely there's a problem with your un-simplified code. If you're willing to share your original snippet I might be able to help.

**Comment by abrownsword** [comment]
Yeah.  I’ll poke at it some more and if I can’t make it work will try to create a repro case that is as simple as possible but no simpler.  :)

**Comment by abrownsword** [comment]
Oh (duh on my part)... I just realized that in your example you have the keys having null values.  In my case the keys are entirely _absent_.  Does the DefaultCodable support missing keys?  Is there any way to support this?  I want a solution for versioning structs by adding fields which never existed before, but still being able to load old data.

**Comment by abrownsword** [comment]
I get this error if I remove one of the keys:  
`Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "b", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "t", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"b\", intValue: nil) (\"b\").", underlyingError: nil))`

**Comment by marksands** [comment]
@abrownsword Since I don't have context into the whole picture, I am making certain assumptions about your code. Are _all_ of your keys missing or are only _some_ null? If they're all missing then you'll need to make the parent object be `DefaultCodable` as well. For completeness:

```swift
struct DefToZero: DefaultCodableStrategy {
  static var defaultValue: Double { 0.0 }
}

typealias DefaultToZero = DefaultCodable<DefToZero>

struct T: Hashable, Equatable, Codable {
  @DefaultToZero var a: Double
  @DefaultToZero var b: Double
  var c: Double
}

struct EmptyT: DefaultCodableStrategy {
  static var defaultValue: T { .init(a: 0, b: 0, c: 42) }
}

typealias DefaultToEmptyT = DefaultCodable<EmptyT>

struct C : Hashable, Equatable, Codable {
  @DefaultToEmptyT var t: T
}

let json = #"{ "t": null }"#.data(using: .utf8)!
let example1 = try! JSONDecoder().decode(C.self, from: json)

example1.t.a
example1.t.b
example1.t.c

let json2 = #"{ "t": { "c": 3.0 } }"#.data(using: .utf8)!
let example2 = try! JSONDecoder().decode(C.self, from: json2)

example2.t.a
example2.t.b
example2.t.c
```

I hope this helps!

**Comment by abrownsword** [comment]
Also, most of my DefaultCodableStrategy derived classes actually just return a defaultValue which is a default constructed instance of the type (i.e. { T() }).  It would be awfully convenient if this were the default behaviour.  Or is there a way to do that?  I suppose I could create a generic, but it seems like it ought to be a common enough case to be included in BetterCodable directly.

**Comment by marksands** [comment]
> Rather than loading the T's in the array and defaulting their missing fields, instead the @DefaultEmptyArray is kicking in and I'm just getting an empty array. 
That sounds like it should work. Maybe something else is going on? If you're able to reproduce a smaller sample case I might be able to help, sorry!

**Comment by abrownsword** [comment]
This exhibits the problem:

`
struct myDefToZero: DefaultCodableStrategy {
  static var defaultValue: Double { 0.0 }
}
typealias myDefaultToZero = DefaultCodable<myDefToZero>

struct T: Hashable, Equatable, Codable {
	@myDefaultToZero var a: Double = 0.0
	@myDefaultToZero var b: Double = 0.0
	@myDefaultToZero var c: Double = 0.0
}

struct EmptyT: DefaultCodableStrategy {
	static var defaultValue: T { T() }
}
typealias DefaultToEmptyT = DefaultCodable<EmptyT>

struct C : Hashable, Equatable, Codable {
	@DefaultEmptyArray var t: [T] = []
}

func test() {
	let json = #"{ "t": [ {"a":9,"b":99,"c":999 } ] }"#.data(using: .utf8)!
	let example1 = try! JSONDecoder().decode(C.self, from: json)

	if example1.t.count > 0 {
		print(example1.t[0].a)
		print(example1.t[0].b)
		print(example1.t[0].c)
	}
	else {
		print("empty array")
	}

	let json2 = #"{ "t": [ {"a":9,"b":99 } ] }"#.data(using: .utf8)!
	let example2 = try! JSONDecoder().decode(C.self, from: json2)

	if example2.t.count > 0 {
		print(example2.t[0].a)
		print(example2.t[0].b)
		print(example2.t[0].c)
	}
	else {
		print("empty array")
	}
}
`

It prints empty array at the end.

**Comment by marksands** [comment]
@abrownsword it's odd that you're getting different results than I am. I ran your code in a playground and it prints:

```
9.0
99.0
999.0
9.0
99.0
0.0
```

It seems that your problem likely lies elsewhere?

**Comment by abrownsword** [comment]
Well you're ahead of me -- I don't even know how to get your package into a playground!

I'm calling my code from the application function in my AppDelegate running on the Mac under the latest xcode & OSX.

**Comment by abrownsword** [comment]
Well I figured out how to get the package into a playground (for the curious:  https://github.com/finestructure/Arena), and now when I run exactly the same code copy&pasted into the playground... it works!

This leaves me mystified as to why it doesn't work in an actual application, however.  What is different about a playground vs an application?

**Comment by marksands** [comment]
@abrownsword 

> What is different about a playground vs an application?
A lot, actually! 😆 

But I imagine it's simply a matter of simplifying your steps to reproduce the issue. I would start with your entire Codable Structs, make sure it fails in the playground, and then reduce the code to further narrow it down to the issue you're experiencing. Then it'll be easier to help. I'm afraid right now it's hard to speculate from my keyboard.

**Comment by abrownsword** [comment]
I’m not sure how to simplify it down past the code above.  Exactly the same code in one fails in the other.  And the code pasted above that you tried is completely separate from the rest of my program, and I’m running it first right as the program starts.
