### ISSUE TITLE
Update BetterCodable Version

### ISSUE THREAD

**Issue by serjooo** [marksands/BetterCodable#19]
Hey Mark! I just tried to use BetterCodable on a package I'm working on and realized that adding the dependency this way `.package(url: "https://github.com/marksands/BetterCodable.git", from: "0.0.0")` is picking 0.0.1 without the latest changes. This is because the release tag points to an earlier commit. I think we might need to do another release to have everyone use the latest changes.

**Comment by marksands** [comment]
🤘 I just tagged `0.1.0`. Let me know if that doesn't work for you.

Cheers!
