### ISSUE TITLE
YearMonthDayStrategy date formatter time zone & locale

### ISSUE THREAD

**Issue by viktorasl** [marksands/BetterCodable#2]
Hello,

https://github.com/marksands/BetterCodable/blob/54ca78204c9db83c321f88ae213103b3837d0c72/Sources/BetterCodable/YearMonthDayStrategy.swift#L11
Shouldn't date formatter be configured like this:
```swift
dateFormatter.timeZone = TimeZone(secondsFromGMT: 0)!
dateFormatter.locale = Locale(identifier: "en_US_POSIX")
```

**Comment by marksands** [comment]
Fixed in 6e32921!
