### ISSUE TITLE
[Feature request] LosslessArray

### ISSUE THREAD

**Issue by igorkulman** [marksands/BetterCodable#24]
Similar to `LosslessValue`, just on working or arrays.

Example:

```swift
struct S {
    @LoselessArray var groupIds: [String]
}
````

would decode 

```json
{
    "groupIds": ["1","2","3"]
}
```
and also

```json
{
    "groupIds": [1,2,3]
}
```

**Comment by marksands** [comment]
👍 I pushed 313471c but won't tag a release until I clean up the code and add docs.
