### ISSUE TITLE
[Question] Working with optional

### ISSUE THREAD

**Issue by igorkulman** [marksands/BetterCodable#26]
Is there a way to combine the property wrapper with optionality?

Say I have

```swift
struct S {
     let timestamp: Date?
}
```

I want the `timestamp` property to be decoded using a custom strategy, but

```swift
struct S {
     @DateValue<TimestampStrategy> var timestamp: Date?
}
```

does not build because the `timestamp` property is optional.

Is there a way to make it work? 

I tried defining a date strategy on optional types but that does not work.

**Comment by igorkulman** [comment]
Same problem trying to apply `@LosslessValue` to an optional property.

**Comment by marksands** [comment]
As a workaround for now you can try:

```swift
struct S {
      var timestamp: DateValue<TimestampStrategy>?
}
```

You lose the property wrapper, but you can still get get the `Date?` from calling `timestamp.wrappedValue`. I don't think there's a good workaround without introducing a new PW type like `@OptionalDateValue`, unless anyone has suggestions. I'll think about it some.

**Comment by AlexNsbmr** [comment]
@marksands do you think it's possible to implement such a notation:  `@OptionalDateValue<TimestampStrategy> var timestamp: Date?`
Tried to work on it but dealing with empty data failure triggered by the `public init(from decoder: Decoder) throws` instantiation.

**Comment by marksands** [comment]
@AlexNsbmr You have to duplicate the strategy as well, which is why I don't want to pursue that implementation for this library. Here's a working example, you're welcome to use it https://gist.github.com/marksands/243cc6963aa4cf23a4d12ecc2b51f44a

**Comment by AlexNsbmr** [comment]
@marksands thanks you for your answer and your exemple. 
Sorry, I wasn't very precise about what was not working. Actually it's working with:
`  let jsonData = #"{"timestamp": null}"#.data(using: .utf8)!`
But not when the key is missing with an empty body for exemple:
  `  let jsonData = #"{}"#.data(using: .utf8)!`

**Comment by marksands** [comment]
@AlexNsbmr in that case you can use the generic type by itself and fetch the internal `wrappedValue` for the optional date. Something like this:

```swift
struct Fixture {
  var timestamp: OptionalDateValue<OptionalTimestampStrategy>?
}

extension Fixture {
  var timestampDate: Date? {
    return timestamp?.wrappedValue
  }
}
```

**Comment by AlexNsbmr** [comment]
@marksands Yes it could work like that but we need to declare a second variable and the variable declaration is not homogeneous because we don't use the same notation. 

Anyway, thank you for the suggestion and keep up the great work ! :)

Hope there will be some changes in `Codable` or  in `WrapperProperty` in the future to allow such a notation.

**Comment by AlexNsbmr** [comment]
Actually I fixed it with:

```
func decode<T>(_ type: OptionalDateValue<T>.Type, forKey key: Self.Key) throws -> OptionalDateValue<T> {
    return try decodeIfPresent(type, forKey: key) ?? OptionalDateValue<T>(wrappedValue: nil)
}
```

**Comment by guidedways** [comment]
@AlexNsbmr Can you share the full solution?

**Comment by AlexNsbmr** [comment]
@guidedways yes sure, actually it's the same solution that @marksands suggested:

https://gist.github.com/marksands/243cc6963aa4cf23a4d12ecc2b51f44a

You just need to add https://github.com/marksands/BetterCodable/issues/26#issuecomment-693233564 in addition to that

**Comment by SajjadKharrazi** [comment]
in my json sometimes exists `timestamp` and sometimes does not exist.
i want to have `timestamp` like this with `Date()` as default value if does not exist or is `null`:

``` swift 
struct Fixture: Codable {
  @OptionalDateValue<OptionalTimestampStrategy> var timestamp: Date
} 
```

how can i do this?
