### ISSUE TITLE
Composing `LossyArray` with `DefaultEmptyArray`

### ISSUE THREAD

**Issue by andrekandore** [marksands/BetterCodable#34]
Hi

I have a need to be able to handle both 
1. lossy array (some items cant be decoded) 
2. default empty (for when the property itself is not present).

## Issue
I tried to compose those with something like:
```
  @DefaultEmptyArray
  @LossyArray
  var items: [Item]
```

but I get the swift compiler error 
```
Property type '[Model.Item]' does not match that of the 'wrappedValue' property of its wrapper type 'DefaultEmptyArray'
```

## Cause
This seems because one of the two types arent able to wrap the other (both want to take the original `T`).

## Proposed Fix
To fix this I have done the following:

```
struct DefaultLossyArray<T: Codable>: DefaultCodableStrategy {
  static var defaultValue: LossyArray<T> { .init(wrappedValue: []) }
}

typealias EmptyLossyArray<T> = DefaultCodable<DefaultLossyArray<T>> where T: Codable
```

with this addition I can hadle the above two cases well.

```
  @EmptyLossyArray
  @LossyArray
  var items: [Item]
```

## Pull Request
Do you feel something like this is worth adding to `BetterCodable`?

Please let me know, I can send a PR w/tests etc.

Thanks!

**Comment by marksands** [comment]
Adding a custom `DefaultCodableStrategy` like this is exactly why it's there 🙂.

But this does bring up 2 points that I've seen come up:

1. I'd like for this repository to be more of a foundation to facilitate building extensions. With some few exceptions covering the most common cases. But should I open another repo, such as BetterCodableExt or BetterCodableSnippets, that might contain a wider variety of these sorts of defaults?
2. Somewhat related to the first point, this one feels slightly in the middle. But it also touches upon property wrapper composition. I'd like to dive more into what's necessary to make some or all of these structs able to be nested, which might lead to more interesting finds.

I'll close this issue for now but leave the conversation open for future discussion.

**Comment by andrekandore** [comment]
thanks for the quick reply, its appreciated

> 1. I'd like for this repository to be more of a foundation to facilitate building extensions. With some few exceptions covering the most common cases. But should I open another repo, such as BetterCodableExt or BetterCodableSnippets, that might contain a wider variety of these sorts of defaults?

thats completely understandable and appreciate that its small and not a mega framework (one of the reasons im happy to use it ^^)

> 2. Somewhat related to the first point, this one feels slightly in the middle. But it also touches upon property wrapper composition. I'd like to dive more into what's necessary to make some or all of these structs able to be nested, which might lead to more interesting finds.

yes, absolutely. that would be the big win if they are all seamlessly composable...

thanks!
