### ISSUE TITLE
podspec file should change version to  0.3.0

### ISSUE THREAD

**Issue by chunxige** [marksands/BetterCodable#36]

**Comment by Igor-Palaguta** [comment]
Yes, currently to use 0.3.0 we write:

`pod 'BetterCodable', :git => 'https://github.com/marksands/BetterCodable.git', :tag => '0.3.0'`

Please can you publish new version to pod repo

**Comment by marksands** [comment]
I've pushed the missing podspecs, with 0.4.0 being the latest release.
