### ISSUE TITLE
Default Empty Lossy Array

### ISSUE THREAD

**Issue by lordzsolt** [marksands/BetterCodable#37]
### Currently, you have to choose between:
- `Decoder` not containing the array's key => `@DefaultEmptyArray`
- `Decoder` contains the array's key, but one of the objects cannot be decoded => `@LossyArray`

**But there is no possibility to have both behaviors.**

#### Model: 
```swift
struct User: Codable {
    var name: String
    var boughtArticles: [Article]
}

struct Article: Codable {
    var price: Int
}
```

#### Response JSON possibilities

1. 
```json
{ 
  "name": "abc",
  "bought_articles": [
     { "price": 15 },
     { "proice": 10 } // Miss-typed key
  ]
}
```
2. Because API is doing `omitempty`
```json
{
  "name": "abc"
}
```

In this case, neither possibilities work properly. 
- `@LossyArray` would fail with the 2nd JSON
- `@DefaultEmptyArray` would not fail, but it would be an empty array, and not contain the Article with price 10, that could've been correctly decoded.

----

What are your thoughts on this? How should it be handled?

I can create a `@DefaultEmptyLossyArray`, if there is no better option.

**Comment by chunxige** [comment]
i think This may be considered a server error

**Comment by lordzsolt** [comment]
> i think This may be considered a server error

This example is of course a server issue. But I just used it for the sake of demonstration.

Decoding can fail for multiple reasons, not all of which could be classified as server error. For example a newly added enum case.

```swift
enum ArticleStatus: String, Decodable  {
   case open
   case closed
}
```

If the Server adds a new `ArticleStatus.banished` for example, suddenly decoding the whole `boughtArticles` array will fail.

Ideally, I would just have those elements not included in the array (hence `LossyArray`)

**Comment by marksands** [comment]
Yeah, creating your own custom type like `@DefaultEmptyLossyArray` would be the way to go. Feel free to use this source as inspiration.
