### ISSUE TITLE
Xcode 13 linking against a dylib which is not safe for use in application extensions

### ISSUE THREAD

**Issue by tahirmt** [marksands/BetterCodable#47]
We started getting this warning on Xcode 13 on watchOS extension. I am not sure at the moment what symbol it is using that's extension unsafe but any help would be appreciated

**Comment by marksands** [comment]
I don't believe this is an issue with this library. You might have luck googling for `APPLICATION_EXTENSION_API_ONLY`. If this is still a problem specific to this library, please let me know.
