### ISSUE TITLE
Purpose of LossyDecodableValue in LossyArray

### ISSUE THREAD

**Issue by colinhumber** [marksands/BetterCodable#8]
I'm curious what the purpose of the `LossyDecodableValue` private struct is in the `LossyArray` wrapper. Since the generic `T` type is constrained to be a `Codable` type, couldn't the decoding in the wrapper be changed to:

```
let value = try container.decode(T.self)
```

I was playing around with this and it works as expected. Not sure I'm missing something and would appreciate some insight. Thanks!

**Comment by marksands** [comment]
Yep, you are correct! Not sure what happened there 🤷‍♀
